import { ComputeSize } from "./types";

/**
 * Offline seed data, captured from the Supabase docs on 2026-07-23.
 * Used on first run and whenever a live fetch fails, so the command always
 * shows something. Live fetches overwrite this in LocalStorage.
 */
export const FALLBACK_CAPTURED_AT = "2026-07-23";

export const FALLBACK_SIZES: ComputeSize[] = [
  {
    name: "Nano",
    hourlyPriceUsd: "$0",
    monthlyPriceUsd: "$0",
    cpu: "Shared",
    vcpus: "Shared",
    memory: "Up to 0.5 GB",
    maxDbSize: "500 MB",
    baselineThroughput: "5 MB/s",
    maxThroughput: "261 MB/s",
    baselineIops: "250 IOPS",
    maxIops: "11,800 IOPS",
    maxReplicationSlots: "5",
    maxWalSenders: "5",
    dbMaxConnections: "60",
    poolerMaxClients: "200",
  },
  {
    name: "Micro",
    hourlyPriceUsd: "$0.01344",
    monthlyPriceUsd: "~$10",
    cpu: "2-core (shared)",
    vcpus: "2",
    memory: "1 GB",
    maxDbSize: "10 GB",
    baselineThroughput: "11 MB/s",
    maxThroughput: "261 MB/s",
    baselineIops: "500 IOPS",
    maxIops: "11,800 IOPS",
    maxReplicationSlots: "5",
    maxWalSenders: "5",
    dbMaxConnections: "60",
    poolerMaxClients: "200",
  },
  {
    name: "Small",
    hourlyPriceUsd: "$0.0206",
    monthlyPriceUsd: "~$15",
    cpu: "2-core (shared)",
    vcpus: "2",
    memory: "2 GB",
    maxDbSize: "50 GB",
    baselineThroughput: "22 MB/s",
    maxThroughput: "261 MB/s",
    baselineIops: "1,000 IOPS",
    maxIops: "11,800 IOPS",
    maxReplicationSlots: "5",
    maxWalSenders: "5",
    dbMaxConnections: "90",
    poolerMaxClients: "400",
  },
  {
    name: "Medium",
    hourlyPriceUsd: "$0.0822",
    monthlyPriceUsd: "~$60",
    cpu: "2-core (shared)",
    vcpus: "2",
    memory: "4 GB",
    maxDbSize: "100 GB",
    baselineThroughput: "43 MB/s",
    maxThroughput: "261 MB/s",
    baselineIops: "2,000 IOPS",
    maxIops: "11,800 IOPS",
    maxReplicationSlots: "5",
    maxWalSenders: "5",
    dbMaxConnections: "120",
    poolerMaxClients: "600",
  },
  {
    name: "Large",
    hourlyPriceUsd: "$0.1517",
    monthlyPriceUsd: "~$110",
    cpu: "2-core (dedicated)",
    vcpus: "2",
    memory: "8 GB",
    maxDbSize: "200 GB",
    baselineThroughput: "79 MB/s",
    maxThroughput: "594 MB/s",
    baselineIops: "3,600 IOPS",
    maxIops: "20,000 IOPS",
    maxReplicationSlots: "8",
    maxWalSenders: "8",
    dbMaxConnections: "160",
    poolerMaxClients: "800",
  },
  {
    name: "XL",
    hourlyPriceUsd: "$0.2877",
    monthlyPriceUsd: "~$210",
    cpu: "4-core (dedicated)",
    vcpus: "4",
    memory: "16 GB",
    maxDbSize: "500 GB",
    baselineThroughput: "149 MB/s",
    maxThroughput: "594 MB/s",
    baselineIops: "6,000 IOPS",
    maxIops: "20,000 IOPS",
    maxReplicationSlots: "24",
    maxWalSenders: "24",
    dbMaxConnections: "240",
    poolerMaxClients: "1,000",
  },
  {
    name: "2XL",
    hourlyPriceUsd: "$0.562",
    monthlyPriceUsd: "~$410",
    cpu: "8-core (dedicated)",
    vcpus: "8",
    memory: "32 GB",
    maxDbSize: "1 TB",
    baselineThroughput: "297 MB/s",
    maxThroughput: "594 MB/s",
    baselineIops: "12,000 IOPS",
    maxIops: "20,000 IOPS",
    maxReplicationSlots: "80",
    maxWalSenders: "80",
    dbMaxConnections: "380",
    poolerMaxClients: "1,500",
  },
  {
    name: "4XL",
    hourlyPriceUsd: "$1.32",
    monthlyPriceUsd: "~$960",
    cpu: "16-core (dedicated)",
    vcpus: "16",
    memory: "64 GB",
    maxDbSize: "2 TB",
    baselineThroughput: "594 MB/s",
    maxThroughput: "594 MB/s",
    baselineIops: "20,000 IOPS",
    maxIops: "20,000 IOPS",
    maxReplicationSlots: "80",
    maxWalSenders: "80",
    dbMaxConnections: "480",
    poolerMaxClients: "3,000",
  },
  {
    name: "8XL",
    hourlyPriceUsd: "$2.562",
    monthlyPriceUsd: "~$1,870",
    cpu: "32-core (dedicated)",
    vcpus: "32",
    memory: "128 GB",
    maxDbSize: "4 TB",
    baselineThroughput: "1,188 MB/s",
    maxThroughput: "1,188 MB/s",
    baselineIops: "40,000 IOPS",
    maxIops: "40,000 IOPS",
    maxReplicationSlots: "80",
    maxWalSenders: "80",
    dbMaxConnections: "490",
    poolerMaxClients: "6,000",
  },
  {
    name: "12XL",
    hourlyPriceUsd: "$3.836",
    monthlyPriceUsd: "~$2,800",
    cpu: "48-core (dedicated)",
    vcpus: "48",
    memory: "192 GB",
    maxDbSize: "6 TB",
    baselineThroughput: "1,781 MB/s",
    maxThroughput: "1,781 MB/s",
    baselineIops: "50,000 IOPS",
    maxIops: "50,000 IOPS",
    maxReplicationSlots: "80",
    maxWalSenders: "80",
    dbMaxConnections: "500",
    poolerMaxClients: "9,000",
  },
  {
    name: "16XL",
    hourlyPriceUsd: "$5.12",
    monthlyPriceUsd: "~$3,730",
    cpu: "64-core (dedicated)",
    vcpus: "64",
    memory: "256 GB",
    maxDbSize: "10 TB",
    baselineThroughput: "2,375 MB/s",
    maxThroughput: "2,375 MB/s",
    baselineIops: "80,000 IOPS",
    maxIops: "80,000 IOPS",
    maxReplicationSlots: "80",
    maxWalSenders: "80",
    dbMaxConnections: "500",
    poolerMaxClients: "12,000",
  },
  {
    name: "24XL",
    hourlyPriceUsd: "NA",
    monthlyPriceUsd: "NA",
    cpu: "NA",
    vcpus: "NA",
    memory: "NA",
    maxDbSize: "NA",
    baselineThroughput: "3,750 MB/s",
    maxThroughput: "3,750 MB/s",
    baselineIops: "120,000 IOPS",
    maxIops: "120,000 IOPS",
    maxReplicationSlots: "NA",
    maxWalSenders: "NA",
    dbMaxConnections: "NA",
    poolerMaxClients: "NA",
  },
  {
    name: "24XL - Optimized CPU",
    hourlyPriceUsd: "NA",
    monthlyPriceUsd: "NA",
    cpu: "NA",
    vcpus: "NA",
    memory: "NA",
    maxDbSize: "NA",
    baselineThroughput: "3,750 MB/s",
    maxThroughput: "3,750 MB/s",
    baselineIops: "120,000 IOPS",
    maxIops: "120,000 IOPS",
    maxReplicationSlots: "NA",
    maxWalSenders: "NA",
    dbMaxConnections: "NA",
    poolerMaxClients: "NA",
  },
  {
    name: "24XL - Optimized Memory",
    hourlyPriceUsd: "NA",
    monthlyPriceUsd: "NA",
    cpu: "NA",
    vcpus: "NA",
    memory: "NA",
    maxDbSize: "NA",
    baselineThroughput: "3,750 MB/s",
    maxThroughput: "3,750 MB/s",
    baselineIops: "120,000 IOPS",
    maxIops: "120,000 IOPS",
    maxReplicationSlots: "NA",
    maxWalSenders: "NA",
    dbMaxConnections: "NA",
    poolerMaxClients: "NA",
  },
  {
    name: "24XL - High Memory",
    hourlyPriceUsd: "NA",
    monthlyPriceUsd: "NA",
    cpu: "NA",
    vcpus: "NA",
    memory: "NA",
    maxDbSize: "NA",
    baselineThroughput: "3,750 MB/s",
    maxThroughput: "3,750 MB/s",
    baselineIops: "120,000 IOPS",
    maxIops: "120,000 IOPS",
    maxReplicationSlots: "NA",
    maxWalSenders: "NA",
    dbMaxConnections: "NA",
    poolerMaxClients: "NA",
  },
  {
    name: "48XL",
    hourlyPriceUsd: "NA",
    monthlyPriceUsd: "NA",
    cpu: "NA",
    vcpus: "NA",
    memory: "NA",
    maxDbSize: "NA",
    baselineThroughput: "5,000 MB/s",
    maxThroughput: "5,000 MB/s",
    baselineIops: "240,000 IOPS",
    maxIops: "240,000 IOPS",
    maxReplicationSlots: "NA",
    maxWalSenders: "NA",
    dbMaxConnections: "NA",
    poolerMaxClients: "NA",
  },
  {
    name: "48XL - Optimized CPU",
    hourlyPriceUsd: "NA",
    monthlyPriceUsd: "NA",
    cpu: "NA",
    vcpus: "NA",
    memory: "NA",
    maxDbSize: "NA",
    baselineThroughput: "5,000 MB/s",
    maxThroughput: "5,000 MB/s",
    baselineIops: "240,000 IOPS",
    maxIops: "240,000 IOPS",
    maxReplicationSlots: "NA",
    maxWalSenders: "NA",
    dbMaxConnections: "NA",
    poolerMaxClients: "NA",
  },
  {
    name: "48XL - Optimized Memory",
    hourlyPriceUsd: "NA",
    monthlyPriceUsd: "NA",
    cpu: "NA",
    vcpus: "NA",
    memory: "NA",
    maxDbSize: "NA",
    baselineThroughput: "5,000 MB/s",
    maxThroughput: "5,000 MB/s",
    baselineIops: "240,000 IOPS",
    maxIops: "240,000 IOPS",
    maxReplicationSlots: "NA",
    maxWalSenders: "NA",
    dbMaxConnections: "NA",
    poolerMaxClients: "NA",
  },
  {
    name: "48XL - High Memory",
    hourlyPriceUsd: "NA",
    monthlyPriceUsd: "NA",
    cpu: "NA",
    vcpus: "NA",
    memory: "NA",
    maxDbSize: "NA",
    baselineThroughput: "5,000 MB/s",
    maxThroughput: "5,000 MB/s",
    baselineIops: "240,000 IOPS",
    maxIops: "240,000 IOPS",
    maxReplicationSlots: "NA",
    maxWalSenders: "NA",
    dbMaxConnections: "NA",
    poolerMaxClients: "NA",
  },
];
